{% set version = "2.0.20" %}
{% set checksum = "e0bee8b3a92b7b674891bc9e1fc3bf73ede5837afa87e6c2ac9228a7e095a4b9" %}

package:
  name: z5py
  version: {{ version }}

source:
  url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}
build:
  number: 0
  skip: true  # [win and vc<14]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - xtensor >=0.26,<0.27
    - xtensor-python >=0.28,<0.29
    - xsimd >=13,<14
    - blosc
    - bzip2
    - xz
    - zlib
    - nlohmann_json
    # lz4 builds on conda are broken
    # - lz4-c
  run:
    - python
    - blosc
    - bzip2
    - xz
    - zlib
    # lz4 builds on conda are broken
    # - lz4-c

test:
  imports:
    - z5py
  requires:
    - zarr <3
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
