{% set version = "2.1.2" %}
{% set checksum = "d61fcfea3a05266bc99f0a551c091bbdb4798cf12721df0cf70b49d9a55bba3f" %}

package:
  name: z5py
  version: {{ version }}

source:
  url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
  sha256: {{ checksum }}
build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - cmake
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - ninja  # [win]
    - make  # [not win]
  host:
    - python
    - numpy
    - xtensor >=0.27,<0.28
    - xtensor-python >=0.29,<0.30
    - xsimd >=13,<14
    - blosc
    - bzip2
    - liblzma-devel
    - zlib
    - nlohmann_json
    - lz4-c
  run:
    - python

test:
  imports:
    - z5py
  requires:
    - zarr
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
    - SylvainCorlay
